server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:postgresql://localhost:5433/product_db}
    username: ${PRODUCT_DB_USERNAME:product_user}
    password: ${PRODUCT_DB_PASSWORD:product_pass}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.orderflow.product: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html

orderflow:
  catalog:
    seed:
      enabled: ${ORDERFLOW_CATALOG_SEED_ENABLED:true}

application:
  kafka:
    product-upserted-topic: product.upserted
    product-deleted-topic: product.deleted
